# Generated by Django 4.1.7 on 2023-03-25 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='poll',
            table='poll',
        ),
        migrations.AlterModelTable(
            name='pollanswer',
            table='poll_answer',
        ),
        migrations.AlterModelTable(
            name='pollquestion',
            table='poll_question',
        ),
        migrations.AlterModelTable(
            name='pollvote',
            table='poll_vote',
        ),
        migrations.CreateModel(
            name='PollInviteLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('amount', models.PositiveBigIntegerField()),
                ('usage', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
            options={
                'db_table': 'poll_invite_links',
            },
        ),
    ]
