# Generated by Django 4.1.7 on 2023-03-25 18:01

import apps.poll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_is_private_alter_poll_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollinvitelinks',
            old_name='pool',
            new_name='poll',
        ),
        migrations.AlterField(
            model_name='pollinvitelinks',
            name='link',
            field=models.CharField(default=apps.poll.models._generate_random_code, max_length=255, unique=True),
        ),
    ]
