# Generated by Django 4.1.7 on 2023-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_rename_pool_pollinvitelinks_poll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='meta',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='meta',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='type',
            field=models.CharField(choices=[('TXT', 'Text'), ('NMBR', 'Number'), ('DTE', 'Date'), ('EMAIL', 'Email'), ('TME', 'Time'), ('RNG', 'Range'), ('CHBX', 'CheckBox'), ('RDO', 'Radio')], default=('TXT', 'Text'), max_length=5),
        ),
    ]
