# Generated by Django 4.1.7 on 2023-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_pollquestion_meta_alter_pollanswer_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='meta',
            field=models.CharField(blank=True, default='{}', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='meta',
            field=models.CharField(blank=True, default='{}', max_length=1024, null=True),
        ),
    ]
