# Generated by Django 4.1.7 on 2023-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_pollanswer_meta_alter_pollquestion_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
